from PySide6 import QtWidgets, QtGui, QtCore
from NodeGraphQt import NodeGraph
from ui.nodes.custom_nodes import MaterialNode, ColorNode, BlendNode, TextureNode, UVNode, GradientNode, AddNode
from PySide6.QtGui import QCursor
from ui.custom_viewer import CustomNodeViewer

class NodeEditorView(QtWidgets.QWidget):
    node_selected = QtCore.Signal(str)

    def __init__(self):
        super(NodeEditorView, self).__init__()
        layout = QtWidgets.QVBoxLayout(self)
        self.setLayout(layout)

        self.node_graph = NodeGraph(viewer=CustomNodeViewer())
        self.node_graph_widget = self.node_graph.widget
        layout.addWidget(self.node_graph_widget)

        self.node_graph_widget.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.node_graph_widget.customContextMenuRequested.connect(self.open_context_menu)

        self.node_graph.node_double_clicked.connect(self.on_node_double_clicked)
        self.node_graph.node_selected.connect(self.on_node_selected)

    def open_context_menu(self, position):
        menu = QtWidgets.QMenu(self)
        pos = QCursor.pos()

        add_material_action = menu.addAction("Add Material Node")
        add_color_action = menu.addAction("Add Color Node")
        add_blend_action = menu.addAction("Add Blend Node")
        add_texture_action = menu.addAction("Add Texture Node")
        add_uv_action = menu.addAction("Add UV Node")
        add_gradient_action = menu.addAction("Add Gradient Node")
        add_add_action = menu.addAction("Add Add Node")  # Add AddNode option


        action = menu.exec_(self.node_graph_widget.mapToGlobal(position))

        if action == add_material_action:
            self.add_node(MaterialNode, "Material Node", position)
        elif action == add_color_action:
            self.add_node(ColorNode, "Color Node", position)
        elif action == add_blend_action:
            self.add_node(BlendNode, "Blend Node", position)
        elif action == add_texture_action:
            self.add_node(TextureNode, "Texture Node", pos)
        elif action == add_uv_action:
            self.add_node(UVNode, "UV Node", position)
        elif action == add_gradient_action:
            self.add_node(GradientNode, "Gradient Node", position)
        elif action == add_add_action:
            self.add_node(AddNode, "Add Node", position)  # Handle adding the AddNode


    def contextMenuEvent(self, event):
        self.open_context_menu(event.pos())
        event.accept()

    def add_node(self, node_class, name, pos, **kwargs):
        node = node_class()
        node.set_name(name)
        self.node_graph.add_node(node)
        node.set_pos(pos.x(), pos.y())
        self.update_code_editor()
        return node

    def generate_glsl_code(self):
        generated_code = []
        used_vars = set()
        final_output_var = None


        for node in self.node_graph.all_nodes():
            if hasattr(node, 'generate_glsl'):
                var_name = node.generate_glsl(generated_code, used_vars)
                final_output_var = var_name

        final_code = f"""
    #version 120
    {self.format_glsl_code(generated_code)}

    void main() {{
        gl_FragColor = vec4({final_output_var}, 1.0);
    }}
    """
        print(f"Generated GLSL code:\n{final_code}")
        return final_code

    def format_glsl_code(self, code_lines):
        formatted_code = ""
        indent = "    "
        for line in code_lines:
            if line.strip().startswith("//"):
                formatted_code += f"{line}\n"
            else:
                formatted_code += f"{indent}{line}\n"
        return formatted_code

    def on_node_double_clicked(self, node):
        self.update_code_editor(node)

    def on_node_selected(self, node):
        self.update_code_editor(node)

    def update_code_editor(self, selected_node=None):
        if selected_node and isinstance(selected_node, (GradientNode, UVNode)):
            return

        if selected_node:
            glsl_code = self.generate_glsl_code_for_node(selected_node)
        else:
            glsl_code = self.generate_glsl_code()
        self.node_selected.emit(glsl_code)

    def generate_glsl_code_for_node(self, node):
        generated_code = []
        used_vars = set()

        if hasattr(node, 'generate_glsl'):
            var_name = node.generate_glsl(generated_code, used_vars)
            final_output_var = var_name  # Track the variable generated by this node

        final_code = f"""
    #version 120
    {self.format_glsl_code(generated_code)}

    void main() {{
        gl_FragColor = vec4(vec3({final_output_var}), 1.0);
    }}
    """
        print(f"Generated GLSL code for node:\n{final_code}")
        return final_code
